
name: Check CWL validity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cwltool
      run: |
        sudo apt-get install -qq python3-yaml python3-pip
        sudo pip3 install --force-reinstall cwltool
    - name: YAML syntax validation 
      run: |
        for f in tools/*cwl *.cwl; do
          echo ${f}
          python -c 'import yaml, sys; yaml.safe_load(sys.stdin)' < ${f}
        done
    - name: Validate CWL tool definitions
      run: |
        cd tools
        for f in *.cwl; do
          cwltool --validate ${f}
        done
    - name: Validate CWL workflows
      run: |
        for f in *.cwl; do
          cwltool --validate ${f}
        done

